import { type projectDescriptionContent } from "../../components/project-description/project-description";

export const content: projectDescriptionContent = {
  desc: "For this project we had to implement a tiling algorithm. I immediatly knew that I wanted to create something in 3D and quickly came up with the idea to create a labyrinth of bridges connecting to each other. Since I wanted the player to be able to walk through this labyrinth I implemented the whole project in Godot and compiled it for the web to incorperate it into my website. The tiling algorithm I implemented here is my own and honestly pretty naive, For each Tile I am assuming a cube and creating a bitmask describing the possible connections. Then I keep a 'world grid' which also stores connector masks. If I place a tile somewhere I check whether its connector mask fits into that spot. After I have placed a tile I update all neighboring connector masks to reflect the new tile placed here and its open connections. Also, at the start of the game I create permutations of my tiles by rotating them. (This explanation was somewhat simplified).",
  challenge:
    "Honestly, I had a lot of fun with this, the algorithm was challenging, sure. But I think the thing I struggled most with was creating the bridge tiles in blender, since I had very little blender experience at this point. Because of this the bridge tiles are not very complex, but for this they are enough.",
  good: "I really like the algorithm and the flexiblity the user has. Another thing i really like is the fact that the user can actually walk around the labyrinth because I implemented this project in a game engine.",
  usage:
    "First you have to click on the game, so that your mouse is captured. Then the player controller allows you to walk around the scene, you can also toggle between flight mode using 'F' in which case you can fly up and down using space and shift. To enter the Menu, you have to press escape twice (because the mouse is captured by the browser). In here you can control the tiling algorithm and adjust which tiles are active, how the permutations are created, where they are placed and how fast.",
};
